name: Allure Report

on: 
  workflow_call

jobs:
  autotests:
    name: Run tests and generate Allure Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install tox
        run: |
          if which tox &> /dev/null; then
            echo "tox is already installed."
            tox --version
          fi

          pip_path=$(which pip 2>/dev/null)
          SYSTEM_PIP_PATH="/usr/bin/pip"
          if [ -n "$pip_path" ] && [ "$pip_path" != "$SYSTEM_PIP_PATH" ]; then
              echo "Pip is available and not system-managed. Installing tox"
              pip install tox
          fi

          if which pipx &> /dev/null; then
              echo "Pipx is available. Installing tox"
              pipx install tox
          fi

          echo "Neither pip nor pipx are available. Installing pipx via apt..."
          sudo apt-get update -yqq
          sudo apt-get install -yqq pipx
          pipx ensurepath
          sudo pipx ensurepath

          echo "Installing tox with pipx..."
          pipx install tox

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set branch name
        run: |
          echo "Branch name: ${{ github.ref_name }}"
          echo "Head ref: ${{ github.head_ref }}"
          echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Integration tests variable setting
        run: |
          allure_artifact_suffix=$(uuidgen)
          series=""
          if [ ! -z ${{ matrix.series }} ]; then
            series="--series ${{ matrix.series }}"
            allure_artifact_suffix="$allure_artifact_suffix"-${{ matrix.series }}
          fi
          echo "SERIES=$series" >> $GITHUB_ENV
          module=""
          if [ ! -z ${{ matrix.modules }} ]; then
            module="-k ${{ matrix.modules }}"
            allure_artifact_suffix="$allure_artifact_suffix"-${{ matrix.modules }}
          fi
          echo "MODULE=$module" >> $GITHUB_ENV
          echo "ALLURE_ARTIFACT_SUFFIX=$allure_artifact_suffix" >> $GITHUB_ENV
      
      - name: Install pytest plugin
        run: pip install git+https://github.com/swetha1654/allure-simple@${{ env.BRANCH_NAME }}#subdirectory=python/pytest_plugins/allure_pytest_collection_report

      - name: Collect tests
        run: |
          pytest -k ${{ inputs.module-name }} --allure-collection-dir=allure-default

      - name: Upload Default Allure results
        timeout-minutes: 3
        uses: actions/upload-artifact@v4
        with:
          name: allure-default-results-${{ github.run_number }}-${{ inputs.module-name }}
          path: allure-default/
          if-no-files-found: error

      - name: Run Test
        if: always()
        run: pytest -k ${{ inputs.module-name }} --deselect tests/test_calculator.py::test_add --alluredir=allure-${{ inputs.module-name }}
        continue-on-error: true          

      - name: Upload Allure results
        timeout-minutes: 3
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ github.run_number }}-${{ inputs.module-name }}
          path: allure-${{ inputs.module-name }}
          if-no-files-found: error

