name: Allure Report

on: 
  workflow_call:
    inputs: 
      module-name:
        type: string
        default: something

jobs:
  autotests:
    name: Run tests and generate Allure Report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check code style
        if: always()
        run: |
          flake8

      - name: Run Test
        if: always()
        run: pytest -k ${{ inputs.module-name }} --alluredir=allure-${{ inputs.module-name }}
        continue-on-error: true

      - name: Upload Allure results
        timeout-minutes: 3
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ inputs.module-name }}
          path: allure-${{ inputs.module-name }}
          if-no-files-found: error

